---
- name: Test Playbook
  hosts: all #where to performs the tasks/we can add ip addres and it specifie to perform just one VM only
  become: true
  become_method: sudo #to perform the task to the root user both lines
  connection: ssh
  ignore_errors: false
  tasks:

  