---
- name: Test Playbook
  hosts: all #where to performs the tasks/we can add ip addres and it specifie to perform just one VM only
  become: true
  become_method: sudo #to perform the task to the root user both lines
  connection: ssh
  ignore_errors: false
  tasks:         #it is the template wich we will work everytime
    - name: Handler task
      package: 
        name: httpd
        state: latest
      notify : HTTPD RESTART

    - name: Install MySQL
      package: 
        name: mariadb-server
        state: present   
      notify: MYSQL RESTART


  handlers: 
    - name: Restart apache
      systemd:
        name: httpd
        state: restarted 

    - name: MYSQL RESTART
      systemd: 
        name: mysqld
        state: restarted




    



