---
- name: Install r1soft agent
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    
    - name: Creates a repo
      copy: r1soft.repo
      dest: /etc/yum.repos.d/r1soft.repo


    - name: Install R1soft
      package:
        name: serverbackup-enterprise-agent
        state: latest


    - name: Power off iptables
      systemd:
        name: firewalld
        state: stopped
      ignore_errors: true 
      
      
    - name: Get Key
      shell: r1soft-setup --get-key http://backup.morarutatiana.com
      


    - name: Start R1soft Agent
      systemd: 
        name: sbm-agent
        state: restarted







