---
- name: Test Playbook
  hosts: all #where to performs the tasks/we can add ip addres and it specifie to perform just one VM only
  become: true
  become_method: sudo #to perform the task to the root user both lines
  connection: ssh
  ignore_errors: false
  tasks:         #it is the template wich we will work everytime
    - name: Task Name Here
      ping: 
    - name: Install telnet #second play
      package: 
        name: #name of the package
          - telnet
          - elinks
          - wget
          - unzip
        state: present #
        #latest #if the package doesnt exist it will install latest version, or it can update for you
        #state: present , absent, restarted, stopped, started 
