---
- name:
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Add users 
    user:
      name: "{{ username }}"
      ssh_public_key: "{{ ssh-key }}"
      create_home: yes

  - name: add or removes an SSH authorized key
    authorized_key:
      user: "{{ username }}"
      state: "{{ state }}" 
      key: "{{ new_user_key }}" 
      path: "/home/{{username}}/.ssh/authorized_keys"